# Generated by Django 3.1.7 on 2021-04-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='feedback',
            field=models.TextField(default='It was good'),
            preserve_default=False,
        ),
    ]
