# Generated by Django 3.0.4 on 2021-04-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_transaction_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sentiment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
