# Generated by Django 3.2 on 2021-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210409_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sentiment',
            field=models.IntegerField(),
        ),
    ]
