# Generated by Django 3.2 on 2021-04-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_transaction_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sentiment',
            new_name='compound',
        ),
    ]
