# Generated by Django 3.2 on 2021-04-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_sentiment_transaction_compound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='compound',
            new_name='sentiment',
        ),
    ]
