# Generated by Django 3.2 on 2021-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_compound_transaction_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sentiment',
            field=models.IntegerField(default=0),
        ),
    ]
