# Generated by Django 3.1.7 on 2021-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_transaction_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
