# Generated by Django 3.2 on 2021-04-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20210414_2121'),
        ('management', '0010_customuser'),
    ]

    operations = [
    ]
