# Generated by Django 3.1.7 on 2021-04-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='This is description'),
            preserve_default=False,
        ),
    ]
